### ISSUE TITLE
Generating map from latest stable minetest version (5.2.0) shows unknown nodes in minetestmapper console output

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetestmapper#75] opened 2020-04-23 08:23 UTC
Trying to generate a map last loaded in latest minetest stable version results in warning about unknown nodes while generating output image. The invocation and output is as follows (minetest stable is installed in same parent folder as minetestmapper): 
```
Warning: Falling back to using colors.txt from current directory.
Unknown nodes:
	butterflies:butterfly_violet
	fireflies:hidden_firefly
	butterflies:hidden_butterfly_red
	butterflies:hidden_butterfly_violet
	butterflies:hidden_butterfly_white
	butterflies:butterfly_white
	butterflies:butterfly_red
	fireflies:firefly
```

**Comment by sfan5** [comment] 2020-04-23 10:58
duplicate of #73
Perhaps these nodes should be recognized but not rendered, as to not confuse users.

**Comment by bbros-dev** [comment] 2020-12-24 04:12
Thanks for making this and for making it open source.  Its helping me help my son - good times :)
We hit this error when trying to map the Minetest Clone 2 game.
Perhaps some configuration file mapping `x:y` where `x` is unknown/incoming node name and `y` is the known node name?

This is what we see:

```bash
$ minetestmapper -i ~/snap/minetest/current/worlds/mc2/ -o map.png
Unknown nodes:           
        mcl_core:obsidian
        mcl_mobspawners:spawner 
        mcl_core:cobweb      
        mcl_chests:chest     
        mcl_core:vine        
        mcl_torches:torch_wall
        mcl_core:void               
        mcl_core:clay             
        mcl_flowers:double_fern_top
        mcl_core:stone_with_iron
        mcl_minecarts:rail
        mcl_core:sand
        mcl_core:cobble
        mcl_mushrooms:mushroom_brown
        mcl_core:granite
        mcl_core:lava_source
        mcl_core:bedrock
        mcl_core:stone_with_coal
        mcl_cocoas:cocoa_1
        mcl_cocoas:cocoa_2
        mcl_core:stone_with_lapis
        mcl_core:diorite
        mcl_core:andesite
        mcl_core:leaves
        mcl_core:stone_with_gold
        mcl_core:water_source
        mcl_core:wood
        mcl_flowers:tallgrass
        mcl_core:stone
        mcl_core:stone_with_redstone
        mcl_ocean:kelp_sand
        mcl_core:lava_flowing
        mcl_core:jungleleaves
        mcl_core:reeds
        mcl_core:gravel
       mcl_core:stone_with_diamond
        mcl_farming:melon
        mcl_cocoas:cocoa_3
        mcl_core:jungletree
        mcl_core:dirt_with_grass
        mcl_flowers:fern
        mcl_ocean:seagrass_dirt
        mcl_flowers:double_fern
        mcl_ocean:seagrass_sand
        mcl_core:mossycobble
        mcl_flowers:poppy
        mcl_core:dirt
        mcl_core:tree
        mcl_fences:fence
        mcl_flowers:dandelion
        mcl_core:coarse_dirt
        mcl_core:water_flowing
        mcl_torches:torch
        mcl_mushrooms:mushroom_red
```

**Comment by sfan5** [comment] 2020-12-24 13:06
The colors.txt shipped with minetestmapper is intended for use with Minetest Game, it doesn't work with MineClone.
You'll need a colors.txt generated specifically for use with MineClone.

**Comment by sfan5** [comment] 2020-12-24 13:46
Here's one generated from MineClone2 0.69.0: [colors.txt](https://github.com/minetest/minetestmapper/files/5739766/colors.txt)

**Closed** 2024-10-26 21:00 UTC
