### ISSUE TITLE
minetestmapper command and colors.txt

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetestmapper#4] opened 2014-05-01 12:08 UTC
Hello
I´ve got it work at last.
But there are some I think minor restrictions.
first only the colors.txt in the sources works, at least for me
two the colors.txt must be in the same Folder as the executable.
three the executable must be started from the Folder itself and the colors.txt resided in.

It would be fine if I could use other colors.txt Files and If there were a parameter for the colors.txt for example -c --colors that gives the location of a compatible colors.txt.
But at least it should search for a colors.txt File in the actual Folder it is run from, if there is no such file it should search in ~/.minetest and if theres no to it should at last search in /usr/local/share/minetest/. At last it should be working from anywhere in the FS. For example, The executable is in /usr/local/bin, The color.txt resides in /usr/local/share/minetest/ and my working Directory is /home/user. Let the world be in /home/minetest/.minetest/worlds/World, The output should be in ~/Downloads of user then the resulting command minetestmapper -i /home/.minetest/worlds/World -o ~/Downloads/World-Map.png should work.

It would be a charm to fix that regressions.

Thanks,
JPR

**Comment by sfan5** [comment] 2016-08-09 14:31
duplicate of #27

**Closed by sfan5** 2016-08-09 14:31 UTC
Labels: feature request
